import { Event, User, AnalyticsData } from '@/types';

export const mockUsers: User[] = [
  { id: '1', email: 'admin@university.edu', name: 'Dr. Sarah Johnson', role: 'admin', department: 'Administration', avatar: '' },
  { id: '2', email: 'organizer@university.edu', name: 'Prof. Michael Chen', role: 'organizer', department: 'Computer Science', avatar: '' },
  { id: '3', email: 'student@university.edu', name: 'Alex Rivera', role: 'student', department: 'Engineering', avatar: '' },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'AI & Machine Learning Summit 2024',
    description: 'Join us for an immersive two-day summit exploring the latest advancements in artificial intelligence and machine learning. Featuring keynote speakers from leading tech companies and hands-on workshops.',
    date: '2024-03-15',
    time: '09:00',
    venue: 'Main Auditorium, Building A',
    category: 'seminar',
    capacity: 500,
    registeredCount: 423,
    attendedCount: 0,
    status: 'approved',
    organizerId: '2',
    organizerName: 'Prof. Michael Chen',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Spring Cultural Festival',
    description: 'Celebrate diversity with performances, food, and exhibitions from cultures around the world. A vibrant showcase of our university community.',
    date: '2024-03-22',
    time: '14:00',
    venue: 'University Grounds',
    category: 'cultural',
    capacity: 2000,
    registeredCount: 1567,
    attendedCount: 0,
    status: 'approved',
    organizerId: '2',
    organizerName: 'Cultural Committee',
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    title: 'Hackathon: Build for Good',
    description: '48-hour coding marathon where teams compete to build innovative solutions for social impact. Prizes worth $10,000!',
    date: '2024-04-05',
    time: '18:00',
    venue: 'Innovation Hub',
    category: 'workshop',
    capacity: 200,
    registeredCount: 189,
    attendedCount: 0,
    status: 'approved',
    organizerId: '2',
    organizerName: 'Tech Society',
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    title: 'Annual Sports Meet 2024',
    description: 'Inter-departmental athletic competition featuring track & field, swimming, basketball, and more. Show your departmental pride!',
    date: '2024-04-12',
    time: '08:00',
    venue: 'University Stadium',
    category: 'sports',
    capacity: 3000,
    registeredCount: 876,
    attendedCount: 0,
    status: 'pending',
    organizerId: '2',
    organizerName: 'Sports Council',
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    title: 'Research Paper Writing Workshop',
    description: 'Learn effective techniques for academic writing, citation management, and publishing strategies from experienced researchers.',
    date: '2024-03-28',
    time: '10:00',
    venue: 'Library Conference Room',
    category: 'academic',
    capacity: 50,
    registeredCount: 45,
    attendedCount: 0,
    status: 'approved',
    organizerId: '2',
    organizerName: 'Graduate Studies Office',
    createdAt: '2024-02-05',
  },
  {
    id: '6',
    title: 'Alumni Networking Night',
    description: 'Connect with successful alumni from various industries. Build your professional network and explore career opportunities.',
    date: '2024-04-20',
    time: '18:30',
    venue: 'Grand Ballroom',
    category: 'social',
    capacity: 300,
    registeredCount: 234,
    attendedCount: 0,
    status: 'pending',
    organizerId: '2',
    organizerName: 'Alumni Association',
    createdAt: '2024-02-15',
  },
];

export const mockAnalytics: AnalyticsData = {
  totalEvents: 42,
  totalRegistrations: 8750,
  totalAttendance: 7230,
  attendanceRate: 82.6,
  popularEvents: [
    { name: 'Spring Cultural Festival', registrations: 1567 },
    { name: 'Annual Sports Meet', registrations: 876 },
    { name: 'AI Summit', registrations: 423 },
    { name: 'Alumni Night', registrations: 234 },
    { name: 'Hackathon', registrations: 189 },
  ],
  departmentParticipation: [
    { department: 'Engineering', count: 2450 },
    { department: 'Business', count: 1890 },
    { department: 'Sciences', count: 1560 },
    { department: 'Arts', count: 1230 },
    { department: 'Medicine', count: 980 },
    { department: 'Law', count: 640 },
  ],
  monthlyTrends: [
    { month: 'Sep', events: 8, registrations: 1200 },
    { month: 'Oct', events: 12, registrations: 1800 },
    { month: 'Nov', events: 10, registrations: 1500 },
    { month: 'Dec', events: 6, registrations: 900 },
    { month: 'Jan', events: 9, registrations: 1350 },
    { month: 'Feb', events: 11, registrations: 1650 },
    { month: 'Mar', events: 14, registrations: 2100 },
  ],
};
